"""Stamp the commit into the package so a built binary's ``--version`` is honest.

Run this **immediately before** PyInstaller (see ``.github/workflows/release-cli.yml``
and the local-build recipe below). It writes ``pandan_cli/_build_stamp.py``, which
``pandan_cli/build_info.py`` imports at runtime; ``--collect-submodules pandan_cli``
sweeps it into the onefile. The file is git-ignored and generated — never commit it,
or a source checkout would start claiming to be a release (V50, KAN-435).

Local build, from ``pandan-cli/``::

    uv run python packaging/stamp_build.py
    uv run --group build pyinstaller --onefile --name pandan-local \\
      --collect-submodules pandan_cli --collect-submodules pandan_client \\
      packaging/pyinstaller_entry.py
    ./dist/pandan-local --version     # -> pandan 0.5.0 (<short sha of HEAD>)
    rm pandan_cli/_build_stamp.py     # back to an honest source run

Where the sha comes from, first hit wins: ``argv[1]`` → ``$PANDAN_BUILD_SHA`` →
``$GITHUB_SHA`` (always set in Actions, so CI needs no git) → ``git rev-parse``
in this checkout. A dirty working tree gets a ``-dirty`` suffix, because a build
from uncommitted code is exactly the "which code is this?" case the stamp exists
to answer. Nothing here runs at CLI runtime — a released binary has no repo.
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

SHA_LEN = 7
STAMP_PATH = Path(__file__).resolve().parent.parent / "pandan_cli" / "_build_stamp.py"


def _git(*args: str) -> str | None:
    try:
        out = subprocess.run(
            ["git", *args],
            cwd=STAMP_PATH.parent,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return out.stdout.strip() or None


def _is_dirty() -> bool:
    # `git status --porcelain` is empty on a clean tree. Untracked files count as
    # dirty here too: an untracked module can change what the binary does.
    status = _git("status", "--porcelain")
    return bool(status)


def resolve_sha(argv: list[str]) -> str:
    if len(argv) > 1 and argv[1].strip():
        return argv[1].strip()[:SHA_LEN]
    for env in ("PANDAN_BUILD_SHA", "GITHUB_SHA"):
        value = (os.environ.get(env) or "").strip()
        if value:
            return value[:SHA_LEN]
    sha = _git("rev-parse", f"--short={SHA_LEN}", "HEAD")
    if not sha:
        # No sha available at all: refuse to invent one. An unstamped build still
        # works, it just reports itself as a source run.
        raise SystemExit(
            "stamp_build: no commit sha available (pass one as argv[1], set "
            "PANDAN_BUILD_SHA, or run inside a git checkout)"
        )
    return f"{sha}-dirty" if _is_dirty() else sha


def main(argv: list[str] | None = None) -> int:
    sha = resolve_sha(argv if argv is not None else sys.argv)
    STAMP_PATH.write_text(
        '"""Generated by packaging/stamp_build.py at package time. Do not commit."""\n'
        f'BUILD_SHA = "{sha}"\n',
        encoding="utf-8",
    )
    print(f"stamp_build: wrote {STAMP_PATH} (BUILD_SHA={sha})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
