"""cycle explicit close (M8 V59, KAN-980)

Adds ``closed_at`` (nullable timestamptz; NULL = open, the existing behaviour,
untouched) plus ``frozen_committed`` / ``frozen_completed`` (nullable JSON, the
``{"count": int, "points": int}`` snapshot captured at close time from the same
live query ``cycle_metrics`` runs today). Purely additive — no data backfill,
mirroring V57's own ``cycle`` column-add migration (``a34847829681``).

Revision ID: 18bcb25e4f91
Revises: a34847829681
Create Date: 2026-09-02 18:09:26.559041
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18bcb25e4f91'
down_revision: Union[str, None] = 'a34847829681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cycle', sa.Column('frozen_committed', sa.JSON(), nullable=True))
    op.add_column('cycle', sa.Column('frozen_completed', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cycle', 'frozen_completed')
    op.drop_column('cycle', 'frozen_committed')
    op.drop_column('cycle', 'closed_at')
    # ### end Alembic commands ###
