"""label emoji (M8 V64, KAN-985)

Adds ``label.emoji`` (nullable varchar(8), issue #278) — a second, independent
visual dimension from ``label.color`` so two labels sharing a colour are still
distinguishable at a glance (SHAPING D12). Any single Unicode grapheme cluster,
not a fixed palette; validated at the schema layer
(``app.emoji.is_single_grapheme``), not by a DB constraint. Purely additive —
no backfill, mirroring V63's own column-add migration (``9a4414056063``).

Revision ID: 6a252bfbdd11
Revises: 9a4414056063
Create Date: 2026-09-03 14:18:33.174026
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a252bfbdd11'
down_revision: Union[str, None] = '9a4414056063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('emoji', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'emoji')
    # ### end Alembic commands ###
