"""notification store (V37, KAN-301)

Revision ID: 6ae1a2ecfb4a
Revises: f7b35130c1f4
Create Date: 2026-07-25 01:24:55.786280
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = '6ae1a2ecfb4a'
down_revision: Union[str, None] = 'f7b35130c1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('board_id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('needs_human', 'blocked', 'ci_failed', 'assigned')", name='ck_notification_kind'),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_board_id'), 'notification', ['board_id'], unique=False)
    op.create_index(op.f('ix_notification_card_id'), 'notification', ['card_id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_card_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_board_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
