"""epic color (M8 V63, KAN-984)

Adds ``epic.color`` (nullable varchar(32), issue #278) — drawn from the same
seven-token palette as ``label.color`` (M8 V62) and validated the same way
(``app.palette.is_valid_label_color``), rather than a second palette. Nullable
because, unlike a label, an epic's color is not required: an uncolored epic
just keeps today's fixed neutral chip look. Purely additive — no backfill,
mirroring V59's/V57's own column-add migrations.

Revision ID: 9a4414056063
Revises: 18bcb25e4f91
Create Date: 2026-09-03 13:50:26.663156
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4414056063'
down_revision: Union[str, None] = '18bcb25e4f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epic', sa.Column('color', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('epic', 'color')
    # ### end Alembic commands ###
