"""board outbound webhook settings (V38, KAN-302)

Revision ID: a4f5050820ce
Revises: 6ae1a2ecfb4a
Create Date: 2026-07-25 01:52:19.150058
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f5050820ce'
down_revision: Union[str, None] = '6ae1a2ecfb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('outbound_webhook_url', sa.Text(), nullable=True))
    op.add_column('board', sa.Column('outbound_webhook_secret', sa.Text(), nullable=True))
    op.add_column('board', sa.Column('outbound_webhook_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'outbound_webhook_enabled')
    op.drop_column('board', 'outbound_webhook_secret')
    op.drop_column('board', 'outbound_webhook_url')
    # ### end Alembic commands ###
